---
title: 前端监控 - 异常监控
date: 2019-06-16 22:00:00
tags: 前端监控
---

## 核心内容：**sourcemap**、**错误发现和收集**、**错误统计和上报**、**错误监控和分析**、**堆栈信息还原**

## **为什么我们需要对错误进行监控？**

在生产环境，大多数web应用（尤其中小型公司）还是没有（或没有成本去实现）完善的单元测试或者自动化测试，使得程序在使用中会泄露众多BUG。 当应用发布到生产环境时出现BUG会造成糟糕的用户体验，甚至影响整个程序的运行。所以，我们需要一种可靠的手段监控应用的健康，并在发生错误时迅速的定位问题、反馈问题。

而前端代码总是通过编译、转换混淆和压缩后发布到生产环境，使得定位错误困难重重。

### **错误监控系统？**

程序运行时将发生各种错误，在不影响程序运行的情况下，将错误快速有效地收集、统计，反馈到管理中心，便于研发更快发现和修复错误地一套系统便是错误监控系统。一般错误监控系统包含三个核心模块：

- **错误发现和收集**：在程序运行中发生错误时，及时监测错误发生的位置、类型并将其收集起来；
- **错误统计和上报**：收集到错误信息后，可能会进行临时缓存、过滤、简单加工或者简单统计等操作，然后将信息上报给统计系统后端存储；
- **错误监控和分析**：错误监控服务面向研发，一般私有部署在公司内部。监控部分接收客户端监听错误、主动上报错误、日志等信息，并存储和统计；分析部分将收集的信息和错误源信息以列表、图表等形式展示，方便研发人员查阅。生产环境的错误一般发生在代码编译和混淆之后，错误信息已经很难定位代码位置，所以，分析部分通常还有**堆栈信息还原**、**代码定位**等功能。

## 错误发现和收集

### 常见的错误类型

**1. 常见js错误**

```jsx
// SyntaxError 语法错误，一般编译检查会过滤掉

// TypeError 数据类型不一致
const fn = (obj) => obj.name
fn(null)

// RangeError 内存溢出，堆栈溢出，死循环，无限递归等等

// 网络错误
// ResourceError 资源加载错误
new Image().src = "路径不存在或者请求你出问题"

// 接口错误没有catch
fetch("api") /* .catch(e => ...)*/

// 没有处理的异步错误
const fn = async () => {
  // error
}
new Promise(() => {
  // error
})

```

**2. Vue错误捕获**

vue通过全局配置errorHandler收集错误
不能捕获 语法错误，跨域请求错误，第三方库的内部错误，

```jsx

  Vue.config.errorHandler = (err, instance, info) => {};

```

**3. React ErrorBoundary**

react通过声明错误边界组件收集错误信息。

```jsx
class ErrorBoundary extends React.Component {
  componentDidCatch(error, errorInfo) {
    errorService.reactErrorAdapter(error, errorInfo);
  }
}

```

### 错误并不好收集

**1. try/catch**无法捕获**语法**和**异步**错误

```jsx
// 语法错误，不能捕获 ❌
try {
 const notdefined,
} catch(e) {
 console.log('捕获到异常：', e);
}

// 异步错误，不能捕获 ❌
try {
 setTimeout(() => {
   console.log(notdefined);
 }, 0)
} catch(e) {
 console.log('捕获到异常：',e);
}
try {
 new Promise((resolve,reject) => {
   JSON.parse('')
   resolve();
 })
} catch(err) {
 console.error('catch', err)
}

```

**2. window.onerror**可以捕获运行时错误和异步错误，无法捕获**语法**错误和**资源**错误

```jsx
window.onerror = function(message, source, lineno, colno, error) {
 console.log('捕获到异常：',{message, source, lineno, colno, error});
}

// 常规运行时错误，可以捕获 ✅
console.log(notdefined);

// 异步错误，可以捕获 ✅
setTimeout(() => {
 console.log(notdefined);
}, 0)

// 语法错误，不能捕获 ❌
const notdefined,

// 资源错误，不能捕获 ❌
// <img src="assets.png">

```

**3. window.addEventListener(“error”)**无法捕获**new Image**和**fetch**

> 当一项资源（如图片或脚本）加载失败，
> 
> 
> **加载资源**
> 
> **不会向上冒泡**
> 
> **但能被捕获**
> 

```jsx
<script>
   window.addEventListener('error', (error) => {
       console.log('捕获到异常：', error);
   }, true)
</script>
// 图片、script、css加载错误，都能被捕获 ✅
<img src="https://example.com/image/kkk.png" alt="">
<script src="resources.js"></script>
<link href="resources.css" rel="stylesheet"/>
<script>
// new Image错误，不能捕获 ❌
new Image().src = 'https://example.com/image/lll.png'

// fetch错误，不能捕获 ❌
fetch('api/v1/data')
</script>
```

**4. window.addEventListener("unhandledrejection")**可以捕获Promise错误

```jsx
// 全局统一处理Promise
window.addEventListener("unhandledrejection", function(e){
 console.log('捕获到异常：', e);
});
fetch('api/v1/data')

```

**5. wrap了fetch api的promise会发送错误的reject**

```jsx
// 例如包装原生fetch api
const f = window.fetch;
window.fetch = function () {
  const p = f.apply(this, arguments)
  // 而`p.then`这个新的promise chain总会返回一个错误的reject信息
  p.then(function() {
    console.log('hi.');
  })

  return p;
}

```

有很多情况下，另一些工具库或者广告拦截器会包装原生fetch api，这些api会拦截函数执行，并将结果重新返回。这个总是reject的错误会在处理过程（上报 >> reject >> 收集 >> 上报 >> reject ...）中引发无限循环。因此，我们需要拿到window上的原生fetch。

```jsx
let cachedFetchImpl: FetchImpl | undefined = undefined

export type FetchImpl = typeof fetch

const isNativeFetch = (func: Function): boolean => {
  return func && /^function fetch\(\)\s+\{\s+\[native code]\s+}$/.test(func.toString())
}

const getNativeFetch = () => {
  if (cachedFetchImpl) return cachedFetchImpl

  if (isNativeFetch(window.fetch)) {
    return (cachedFetchImpl = window.fetch.bind(window))
  }

  const document = window.document
  let fetchImpl = window.fetch

  if (document && typeof document.createElement === 'function') {
    try {
      const sandbox = document.createElement('iframe')
      sandbox.hidden = true
      document.head.appendChild(sandbox)
      const contentWindow = sandbox.contentWindow
      if (contentWindow && contentWindow.fetch) {
        fetchImpl = contentWindow.fetch
      }
      document.head.removeChild(sandbox)
    } catch (e) {
        console.error('Could not create sandbox iframe for pure fetch check: ', e)
    }
  }

  return (cachedFetchImpl = fetchImpl.bind(window))
}

```

### 错误收集实现

**全局简单地通过三种方式监听错误**

```jsx
// listener.ts
export interface IReportData {
  lineno: number
  colno: number
  type: string
  message?: string
  stack?: string
}

export const startListener = () => {
  window.onerror = (message = "", url = "", lineno = -1, colno = -1, error) => {
    // console.log("onerror", error)
    reportError({
      type: "onerror",
      lineno,
      colno,
      message: message as string,
      stack: (error as any)?.stack || ""
    })
  }
  window.addEventListener("error", (event) => {
    const { lineno, colno, message } = event
    // console.log("addEventListener", event)
    reportError({
      type: "addEventListener",
      lineno,
      colno,
      message,
      stack: event.error?.stack || ""
    })
  })
  // promise错误无法拿到位置信息
  window.addEventListener("unhandledrejection", (e) => {
    // console.log("unhandledrejection", e)
    reportError({
      type: "unhandledrejection",
      lineno: -1,
      colno: -1,
      message: e.reason?.message || "",
      stack: e.reason?.stack || ""
    })
  })
}

```
拿到错误信息和位置信息之后，就要考虑如何将生产环境的代码映射到源代码上了。实现这个功能，我们需要一个记录编译前后位置信息的交换文件，**sourcemap**文件。
